package cn.itcast.pojo;

public class Orderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.id
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.ordersId
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    private Integer ordersid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.itemsId
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    private Integer itemsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.itemsNum
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    private Integer itemsnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.id
     *
     * @return the value of orderdetail.id
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.id
     *
     * @param id the value for orderdetail.id
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.ordersId
     *
     * @return the value of orderdetail.ordersId
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public Integer getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.ordersId
     *
     * @param ordersid the value for orderdetail.ordersId
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public void setOrdersid(Integer ordersid) {
        this.ordersid = ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.itemsId
     *
     * @return the value of orderdetail.itemsId
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public Integer getItemsid() {
        return itemsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.itemsId
     *
     * @param itemsid the value for orderdetail.itemsId
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public void setItemsid(Integer itemsid) {
        this.itemsid = itemsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.itemsNum
     *
     * @return the value of orderdetail.itemsNum
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public Integer getItemsnum() {
        return itemsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.itemsNum
     *
     * @param itemsnum the value for orderdetail.itemsNum
     *
     * @mbggenerated Thu Mar 02 16:54:48 CST 2017
     */
    public void setItemsnum(Integer itemsnum) {
        this.itemsnum = itemsnum;
    }
}